### ISSUE TITLE
arrowhead linked with pen width

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#103]
From chrisj0192 #98
> VIDEO MESSAGE CORRECTION about the arrowhead: "I don't know If there is a way that the arrowhead is proportional to the width of its line. I was trying to modify the option values that are available in the option menu (arrowhead: aperture / length) but I couldn't get a proportional arrowhead with its length)"
> This is the video about the arrowhead:
> https://user-images.githubusercontent.com/20199672/120061740-34ac6100-c024-11eb-9433-4329ef946f33.mp4
> Maybe it could solve that problem that when we increase the width of the pen, the arrowhead loses its shape.
> 

Not sure how to code that without major impact. Will think about

_Originally posted by @pubpub-zz in https://github.com/pubpub-zz/ppInk/issues/98#issuecomment-850979427_

**Comment by pubpub-zz** [comment]
other point raised : arrow head in dashed style
Not sure about feasability

**Comment by pubpub-zz** [comment]
@chrisj0192 @NOVAinc
This my proposal:
![image](https://user-images.githubusercontent.com/4083478/121699456-3b7cae80-cacf-11eb-8c37-037fad8ca783.png)

Remember that Arrows are only drawn with lines

[ppInk64_Arr11b.zip](https://github.com/pubpub-zz/ppInk/files/6638987/ppInk64_Arr11b.zip)

**Comment by NOVAinc** [comment]
I have tested it. It works as intended and I like the behavior! I would suggest also making it so that you could control the width of the stroke with pen pressure if you want a bigger or smaller arrow, but I don't know how doable this would be and I guess this might not be consistent with the rest of the program, so as it is it's perfectly good!

**Comment by chrisj0192** [comment]
Hello @ pubpub-zz I was testing this new beta version and I like how good the arrow looks when its line width increases proportionally to the arrowhead. Just amazing!. However I found something odd about the line width. Sometimes it doesn't increase gradually when using shortcuts. Besides that when using the mouse wheel, I noticed that the increase in the line width is different than when using shortcuts.
Here you are a short test video about it. Blue arrows are increased/decreased using mouse wheel.
https://user-images.githubusercontent.com/20199672/121766829-3f81ee00-cb1a-11eb-9c3c-7df8ba4c5d9c.mp4

Well, that's my observation and I pretty like the new arrow!

**Comment by chrisj0192** [comment]
Hello @ pubpub-zz I was testing this new beta version and I like how good the arrow looks when its line width increases proportionally to the arrowhead. Just amazing!. However I found an irregular increase about the line width. Sometimes it doesn't increase gradually when using shortcuts. Besides that when using the mouse wheel, I noticed that the increase in the line width is different than when using shortcuts.

Here you are a short test video about it. Blue arrows are increased/decreased using mouse wheel.
https://user-images.githubusercontent.com/20199672/121767046-90461680-cb1b-11eb-92c9-be642706afea.mp4

Well, that's my observation and I pretty like the new arrow!

**Comment by chrisj0192** [comment]
Hello @pubpub-zz I was testing this new beta version and I like how good the arrow looks when its line width increases proportionally to the arrowhead. Just amazing!. However I found an irregular increase about the line width. Sometimes it doesn't increase gradually when using shortcuts. Besides that when using the mouse wheel, I noticed that the increase in the line width is different than when using shortcuts.

Here you are a short test video about it. Blue arrows are increased/decreased using mouse wheel.
https://user-images.githubusercontent.com/20199672/121767046-90461680-cb1b-11eb-92c9-be642706afea.mp4

Well, that's my observation and I pretty like the new arrow!

**Comment by pubpub-zz** [comment]
> I have tested it. It works as intended and I like the behavior! I would suggest also making it so that you could control the width of the stroke with pen pressure if you want a bigger or smaller arrow, but I don't know how doable this would be and I guess this might not be consistent with the rest of the program, so as it is it's perfectly good!

So far I'm aware of, the pressure is currently internal to Strokes  and  I can not get get them. It is also because of that I cannot save/restorire variable width). Maybe possible with the latest version .NET libraries but It will be a hudge refactoring.

**Comment by pubpub-zz** [comment]
@chrisj0192 
> Hello @pubpub-zz I was testing this new beta version and I like how good the arrow looks when its line width increases proportionally to the arrowhead. Just amazing!. However I found an irregular increase about the line width. Sometimes it doesn't increase gradually when using shortcuts. Besides that when using the mouse wheel, I noticed that the increase in the line width is different than when using shortcuts.

I did the test and for me all looks good. I added some debug in this version:
[ppInk64_invst12b.zip](https://github.com/pubpub-zz/ppInk/files/6642136/ppInk64_invst12b.zip)

Can you redo the test with debug window opened and visible (options / debug window) 
PW= will indicate the new width value

**Comment by chrisj0192** [comment]
Hello @pubpub-zz ,ok I'll redo the test with debug window but ppInk doesn't open by clicking on the main icon, I mean the blue tray icon doesn't show up and I noticed the same issue in #75 .

**Comment by pubpub-zz** [comment]
@chrisj0192 
Oups !
I left some dev code inducing early crash
[ppInk64_invst12c.zip](https://github.com/pubpub-zz/ppInk/files/6642719/ppInk64_invst12c.zip)
fixed. Good also for #75

**Comment by pubpub-zz** [comment]
@chrisj0192 
Any test results inhere ?

**Comment by chrisj0192** [comment]
@pubpub-zz, by the way, I was reading the readme of ppInk and I was wondering if you have thought to improve, change or try to do something new with the edit text. I read that ppInk is a inspiration of EpicPen and something interesting in epicPen is about its edit text. I don't know if it's feasible to integrate or improve in ppInk or how complex is to implement it. These days I've realized that it would be nice and interesting to do ppInk more dynamic in its use with its edit text. The dilemma may be to keep the font and color options? what do you think about it?

Another need that I noticed is about a double headed arrow (a left right arrow? I'm not sure if that's the correct way to write it), tell me, is it feasible to implement it?

**Comment by pubpub-zz** [comment]
(...) in epicPen is about its edit text. I don't know if it's feasible to integrate or improve in ppInk or how complex is to implement it. These days I've realized that it would be nice and interesting to do ppInk more dynamic in its use with its edit text. The dilemma may be to keep the font and color options? what do you think about it?

Edit functions currently implemented allows to modify text, font, size, style, frame. What other functions are you thinking about?

> Another need that I noticed is about a double headed arrow (a left right arrow? I'm not sure if that's the correct way to write it), tell me, is it feasible to implement it?

I thought about this but it is so easy to draw an arrow upon the other and up to now this was not requested. not sure about easiness to implement it

**Comment by chrisj0192** [comment]
> Edit functions currently implemented allows to modify text, font, size, style, frame. What other functions are you thinking about?
I was referring to the way how to write on the screen.
![2](https://user-images.githubusercontent.com/20199672/123547096-03a77500-d725-11eb-9f3a-e5242b3b7228.png)
![1](https://user-images.githubusercontent.com/20199672/123547098-04d8a200-d725-11eb-9e3d-1b668ca16343.png)

>I thought about this but it is so easy to draw an arrow upon the other and up to now this was not requested. not sure about easiness to implement it

I think so,  I'm drawing it wuth arrows,

**Comment by pubpub-zz** [comment]
It has been already asked and the current solution shows directly what you will get even if you get through the edit window. transfering directly the edit on screen will be a hudge work to get selection, insertion point moving,copy/paste...

**Comment by chrisj0192** [comment]
>It has been already asked and the current solution shows directly what you will get even if you get through the edit window. transfering directly the edit on screen will be a hudge work to get selection, insertion point moving,copy/paste...

guessed it... I found it interesting just I was telling you about it because I wanted to know its feasibility.
Thanks,

PS: I don't know whether or not you forgot to reset line styles when using alt, the last time you told me you would add it to your work stack, if you have news about it, please let me know.

> I was trying to combine "line" with "dashed line" and was trying to find an easy way to do it dynamically by setting "alt + d" for the dashed lines. But the dashed line doesn't reset when I release "alt" key.

> Agree with your idea, not sure how to code that yet. Will put that in the stack.

Copied from #98

**Comment by chrisj0192** [comment]
PS2: I found a problem about shape disappearance again using the beta verion ppInk64_varFix14a.zip (it happens few times). I'll try to get that result again using debug mode and another one is pointer disappearance when finishing input a text in edit text and press OK, sometimes arrrow (canvas cursor) is not shown (it also happens sometimes).

**Comment by pubpub-zz** [comment]
from [ https://github.com/pubpub-zz/ppInk/issues/103#issuecomment-869135326]
> Hello @pubpub-zz
> 
> This is my report about pen width:
> 
> First of all, I have to say that my default pen width is 80.
> 
> Test 1 (using mousewheel):
>(...)

I agree about the discrepancy between mouse wheel and hotkeys and that may disturbate users. I modified to use same semi ops for both. I've also modified the default value to be able to return to normal pen width
If you want to try:
[ppInk64_apng 28a.zip](https://github.com/pubpub-zz/ppInk/files/6729439/ppInk64_apng.28a.zip)

about PS(1) : can you create a new issue about it
about PS(2) : thought it was behind...😞 waiting for your captures with debug window opened for analysis

**Comment by chrisj0192** [comment]
Hello @pubpub-zz I tested ppInk64_apng 28a.zip and it's great! it works as expected! The pen width has a more gradual increase and decrease without any problem. Thanks!

about PS(1): I'll create it.
about PS(2): don't worry, I always use ppInk and the shape disappearance it's difficult to find it now because it happens rarely. It may only happens with a shape (line) I'm not sure, but I'll be monitoring that bug. The same thing for canvas cursor disappearance.

**Comment by pubpub-zz** [comment]
> about PS(2): don't worry, I always use ppInk and it's difficult to find shape disappearances now because it happens rarely. It may only happen with a shape (line) I'm not sure, but I'll be monitoring that bug. The same thing for canvas cursor (arrow) disappearance.

Can you clarify ? You've observed dissapearance for something else than line?
Can you clarify for canvas cursor ?

**Comment by chrisj0192** [comment]
Hello @pubpub-zz 
> Can you clarify ? You've observed dissapearance for something else than line?

Yes, I confirm that shapes rarely disappear. I was trying to get results about it but I couldn't get it, it's difficult. When I teach I get that problem (it hardly shows up).

> Can you clarify for canvas cursor ?

On the other hand, I could get results about canvas cursor disappearance (arrow). I was trying to get this problem (I opened the task manager window details tab and also the ppInk debug window).
This is the video:
https://user-images.githubusercontent.com/20199672/124425714-8f755e80-dd2e-11eb-90df-a6a10f1212c1.mp4

Another one is about zoom function (Frozen area). I remember that I had commented on another issue (I forgot to report it)
Shortcut key that I use for the zoom function: M key.
Zoom has strange behavior when I clear my screen (pressing E key) and then I make some strokes and shapes and I press M again to use zoom function, strokes that I deleted appears again on my screen and I need to press M again to use zoom function.

This is the video:
https://user-images.githubusercontent.com/20199672/124428295-22fc5e80-dd32-11eb-9a94-874b95a5ff07.mp4
I've noticed that the canvas cursor (arrow) doesn't show up in the video above. I used it while I was recording this video (I use Camtasia to record). That's odd.

I'll stay tuned to your comments.

Thanks in advance.

**Comment by pubpub-zz** [comment]
> Yes, I confirm that shapes rarely disappear. I was trying to get results about it but I couldn't get it, it's difficult. When I teach I get that problem (it hardly shows up).

If you face such a dissapearance, can you :
* exit inking
* go to options
* open debug

logs are recorded even if the window is closed : you will therefore be able to get the log of the last stroke which would be the one that has dissapeared.

 
> On the other hand, I could get results about canvas cursor disappearance (arrow). I was trying to get this problem (I opened the task manager window details tab and also the ppInk debug window).
> This is the video:
> https://user-images.githubusercontent.com/20199672/124431167-a79cac00-dd35-11eb-90fc-13a66c8e692f.mp4

I've forced the cursor to restore just after text dialog. can you check it is ok for you?

> Another one is about zoom function (Frozen area). I remember that I had commented on another issue (I forgot to report it)
> Shortcut key that I use for the zoom function: M key.
> Zoom has strange behavior when I clear my screen (pressing E key) and then I make some strokes and shapes and I press M again to use zoom function, strokes that I deleted appears again on my screen and I need to press M again to use zoom function.

the cleaning was not reseting the zoom :  the bug is now fixed

also the bug about the saving path from https://github.com/pubpub-zz/ppInk/issues/111#issuecomment-874039279 is fixed also:

[ppInk64_varFix05a.zip](https://github.com/pubpub-zz/ppInk/files/6765801/ppInk64_varFix05a.zip)

**Comment by chrisj0192** [comment]
Hello @pubpub-zz 

> If you face such a dissapearance, can you ...

Ok, I'll do it.

>I've forced the cursor to restore just after text dialog. can you check it is ok for you?

Much better, although canvas cursor disappearance is still present in my case, additionally I noticed with your performance improvements that issue was reduced. I'm thinking it could be a problem with my mouse too. I'll replace it with another in a few days.

> the cleaning was not reseting the zoom : the bug is now fixed.

Fixed! I confirm that this issue has been fixed. 

> also the bug about the saving path from #111 (comment) is fixed also:

About this issue, I still have the same problem with the snapshot saving path. I've not noticed difference.

Thank you.

**Comment by pubpub-zz** [comment]
> Much better, although canvas cursor disappearance is still present in my case, additionally I noticed with your performance improvements that issue was reduced. I'm thinking it could be a problem with my mouse too. I'll replace it with another in a few days.
> 
> >

can you please confirm if the problem occurs immediately after text dialog



> > also the bug about the saving path from #111 (comment) is fixed also:
> 
> About this issue, I still have the same problem with the snapshot saving path. I've not noticed difference.

hope to have the fix tomorrow

**Comment by chrisj0192** [comment]
> can you please confirm if the problem occurs immediately after text dialog

Yes, it happens immediately after closing the text dialog (using ctrl + enter).

**Comment by pubpub-zz** [comment]
I've done more changes, can you tell me if it is better
[ppInk64_varFixes09a.zip](https://github.com/pubpub-zz/ppInk/files/6793958/ppInk64_varFixes09a.zip)
If not can you provide me with your ini files and a video showing the problem. Thanks

**Comment by chrisj0192** [comment]
I've tested ppInk64_varFixes09b.zip and the snapshot saving path is fixed now. It works perfectly!
About the canvas cursor, I need to test it a bit more. For now it seems that there's no problem.

Thank you!
