### ISSUE TITLE
[BUG] pattern on stroke has variable distance and dotted stroke shows up

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#238]
![image](https://user-images.githubusercontent.com/19545604/208000949-19e60096-829b-437e-8b5b-00fc34d70766.png)
It seems the distance between instances varies with cursor speed during the stroke, I'd imagine due to performance, most likely. This example was using a 64x64 clipart and the distance between instances changes according to the cursor speed during a stroke.

On a related note, when the dashed style is selected, the stroke seems to show through instead of staying invisible

**Comment by NOVAinc** [comment]
@pubpub-zz this version has consistently spaced clipart instances! A bug I noticed though was that the clipart box indicator for when you're first choosing the clip's dimensions doesn't seem to be working

**Comment by pubpub-zz** [comment]
I can not reproduce the box indicator issue, can you provide a video ?

**Comment by NOVAinc** [comment]
https://user-images.githubusercontent.com/19545604/209451167-7a814211-f026-4eb1-9d92-c0f9047479c0.mp4

all the pens turned red after I hit ctrl+r, but it was happening like this even before I did that

**Comment by pubpub-zz** [comment]
Ça. You please provide your config and pens file

**Comment by NOVAinc** [comment]
Absolutely! 
[pens-and-config.zip](https://github.com/pubpub-zz/ppInk/files/10304946/pens-and-config.zip)

PS/ Happy Holidays!

**Comment by pubpub-zz** [comment]
Thanks merry Christmas to you too 😀
First remember this release integrates  #240 : when activated (default), pressing shift or control will provide you access to up to 10 more pens. Your pens defines those pens to all as red. This can be disabled when checking off extrapens in  hotkeys option tab

Second, this version also introduced the switch from hand to pen when pressing shift or control to toggle between hand and line to ease drawing straight lines. There was a side effect, when you are using as you did a hotkey that contains ctrl or shift - as you have set scale / rotate to ctrl+R - reseting the tool to hand when releasing. I've fixed it ; can you check it is now ok for you?
Also I've associated this feature to the option setting "alt as as temporary" : you can disable it unchecking the function

give me your feedbacks
[ppInk ctrl in hotkeys.zip](https://github.com/pubpub-zz/ppInk/files/10313445/ppInk.ctrl.in.hotkeys.zip)

**Comment by NOVAinc** [comment]
With that build, I still get the same effect when hitting ctrl+r and trying to insert a clipart afterwards. If I disable the extra pens the clipart still doesn't display the box around it when trying to determine its size. I have also tried disabling "alt as temporary" and the bug is still there. It's no deal breaker but might want to fix it for the next release :D

**Comment by pubpub-zz** [comment]
🤔🤔🤔🤔
can you provide a video and also your hotkeys.ini please

**Comment by NOVAinc** [comment]
https://user-images.githubusercontent.com/19545604/209880459-bc74c82e-6caa-4a55-80b9-c89b00347253.mp4

the hotkeys.ini that I'm using is the one that came in bundled with the zip above. I extracted the archive and tested from that one straight

**Comment by pubpub-zz** [comment]
I've not been able to find the hotkeys.ini not in your previous zip. only config and pens

**Comment by NOVAinc** [comment]
Sorry, I meant your file, not mine. I downloaded and used the bundled build from this post https://github.com/pubpub-zz/ppInk/issues/238#issuecomment-1366515679 to record the video 2 posts above
